- hosts: all

  vars:
    upstream_repository: git@github.com:Cecca/danny.git
    local_repository: ~/danny

  tasks:
    - name: update the repository from upstream
      when: ansible_host == "sss00"
      git:
        repo: "{{ upstream_repository }}"
        dest: "{{ local_repository }}"
        version: "{{ danny_branch }}"

    - name: update the repository locally
      when: ansible_host != "sss00"
      git:
        repo: "sss00:{{ local_repository }}"
        dest: "{{ local_repository }}"
        version: "{{ danny_branch }}"

    - name: compile the code and install
      shell: RUSTFLAGS="-C target-cpu=native" PATH=$PATH:~/.cargo/bin cargo install --path . --force --locked
      args:
        chdir: "{{ local_repository }}/danny"
        executable: /bin/bash

    - name: compile the utilities and install
      shell: RUSTFLAGS="-C target-cpu=native" PATH=$PATH:~/.cargo/bin cargo install --path . --force --locked
      args:
        chdir: "{{ local_repository }}/danny-utilities"
        executable: /bin/bash

