name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        rustup install nightly
        python -m pip install --upgrade pip
        pip install flake8 pyyaml numpy sklearn jinja2
    - name: Build
      run: | 
        cargo +nightly install --path danny
        cargo +nightly install --path danny-utilities
    - name: Build dataset
      run: |
        cd datasets/
        DANNY_DATA_DIR=$(pwd) DANNY_MINIONS=localhost python prepare.py RandomAngular
    - name: Run algorithms
      run: |
        danny --threshold 0.5 --algorithm cartesian datasets/random.bin
        danny --threshold 0.5 --algorithm one-level-lsh --k 2 datasets/random.bin 
        danny --threshold 0.5 --algorithm local-lsh --k 2 datasets/random.bin 
        danny --threshold 0.5 --algorithm two-level-lsh --k 2 --k2 2 datasets/random.bin 
    - name: Run tests
      run: cargo +nightly test --verbose
