name: Rust

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Build dataset
      run: |
        cd experiments/
        DANNY_DATA_DIR=/ DANNY_MINIONS=localhost python run.py --list-datasets --prefix random
    - name: Build
      run: | 
        cargo +nightly build --path danny
        cargo +nightly build --path danny-utilities
    - name: Run tests
      run: cargo +nightly test --verbose
